# 志翔IMU ROS2驱动配置
# 注意: imu设备的输出波特率应与ROS2驱动设置的波特率保持一致
IMU_publisher:
    ros__parameters:
        serial_port: "/dev/ttyUSB0"
        baud_rate: 921600
        frame_id: "base_link"
        imu_topic1: "/imu_data1"
        imu_topic2: "/imu_data2"
        imu_topic3: "/imu_data3"

imu_listener:
    ros__parameters:
        imu_topic1: "/imu_data1"
        imu_topic2: "/imu_data2"
        imu_topic3: "/imu_data3"
